$REMOTE = "o_iseri@speed.encs.concordia.ca"
$SCRATCH = "/speed-scratch/o_iseri/GSSCanada/GSSCanada-main"
$LOCAL   = "C:\Users\o_iseri\Desktop\GSSCanada\GSSCanada-main"

Write-Host "Uploading IDF files..."
scp "$LOCAL\BEM_Setup\Neighbourhoods\NUS_RC1.idf" "${REMOTE}:${SCRATCH}/BEM_Setup/Neighbourhoods/"
scp "$LOCAL\BEM_Setup\Neighbourhoods\NUS_RC2.idf" "${REMOTE}:${SCRATCH}/BEM_Setup/Neighbourhoods/"
scp "$LOCAL\BEM_Setup\Neighbourhoods\NUS_RC3.idf" "${REMOTE}:${SCRATCH}/BEM_Setup/Neighbourhoods/"
scp "$LOCAL\BEM_Setup\Neighbourhoods\NUS_RC4.idf" "${REMOTE}:${SCRATCH}/BEM_Setup/Neighbourhoods/"
scp "$LOCAL\BEM_Setup\Neighbourhoods\NUS_RC5.idf" "${REMOTE}:${SCRATCH}/BEM_Setup/Neighbourhoods/"
scp "$LOCAL\BEM_Setup\Neighbourhoods\NUS_RC6.idf" "${REMOTE}:${SCRATCH}/BEM_Setup/Neighbourhoods/"

Write-Host "Uploading EPW files..."
scp "$LOCAL\BEM_Setup\WeatherFile\CAN_QC_Montreal.Center-Jean.Brebeuf-McGill.Univ-McTavish.716120_TMYx_6A.epw" "${REMOTE}:${SCRATCH}/BEM_Setup/WeatherFile/"
scp "$LOCAL\BEM_Setup\WeatherFile\CAN_ON_Toronto.City-Univ.of.Toronto.715080_TMYx_5A.epw" "${REMOTE}:${SCRATCH}/BEM_Setup/WeatherFile/"
scp "$LOCAL\BEM_Setup\WeatherFile\CAN_MB_Winnipeg.The.Forks.715790_TMYx_7A.epw" "${REMOTE}:${SCRATCH}/BEM_Setup/WeatherFile/"
scp "$LOCAL\BEM_Setup\WeatherFile\CAN_AB_Calgary-Canadian.Olympic.Park.Upper.712350_TMYx_6B.epw" "${REMOTE}:${SCRATCH}/BEM_Setup/WeatherFile/"
scp "$LOCAL\BEM_Setup\WeatherFile\CAN_BC_Vancouver.Harbour.CS.712010_TMYx_5C.epw" "${REMOTE}:${SCRATCH}/BEM_Setup/WeatherFile/"
scp "$LOCAL\BEM_Setup\WeatherFile\CAN_BC_Kelowna.Intl.AP.712030_TMYx_5B.epw" "${REMOTE}:${SCRATCH}/BEM_Setup/WeatherFile/"

Write-Host "Done."
