#!/usr/bin/env python3
"""
3rdJ_06_retail_lever_4split.py  (2026-07-23)  --  Step 6 Track A Part 2 (Leg-3 4-split)

Post-hoc, no-retrain retail-scenario amplitude lever + QC-Sunday sub-axis.
Per runbook 3rdJ_06_longitudinalForecasting_4split.md sections 6B/6G (dr_L3-04
OD-2 RESOLVED, dr_L3-06 SS C.3/C.4):

  Three named scenarios, relative to 2022 = 1.00:
    Plateau/Resilient Central (Default) = 0.97
    Continued-Shift (Conservative)      = 0.90
    In-Store Renaissance (Optimistic)   = 1.05

Mechanics: the scalar multiplies at_retail_fraction_2030(t) BEFORE any Step-7
peak-normalization, so the lever value survives the shape-only injection
(dr_L3-06 SS C.3). This script is a pure post-hoc AMPLITUDE LEVER on the RAW
model-generated 2030 retail-fraction profile -- it does NOT modify any diary
CSV (that is 3rdJ_06_calibrate_C_4split.py's retail-cap stage's job, which
targets observed-2022 x lever instead). Deliverable here is small per-slot
lookup tables, "generated by one lever script" per the runbook's Module
Structure Summary.

Base profile construction: the retail channel is NOT banded by office-WFH
choice (validator gate 5.27: office band selection must leave retail mass
unchanged). So the "base" at_retail_fraction_2030(t) profile is built by
POOLING the three raw per-band 2030 diaries (2030_diaries_{band}_raw.csv) --
they should be near-identical on ret30; this script also PRINTS the
per-band cross-check (evidence for 5.27) before pooling.

QC-Sunday sub-axis (dr_L3-06 SS C.4, runbook OD-1 pre-resolved):
  default = restricted (Sunday ~ 0.60-0.75 x Saturday peak, historical QC
            trading-hours) -- this needs NO manual file-level intervention:
            the 2005-2022 QC Sunday shapes already encode the restriction
            naturally through QC respondents, and the model was trained on
            that real signal, so the DEFAULT lever files below carry it
            through as-generated (no separate deregulated-vs-restricted
            branch for the 3 primary files).
  optimistic (deregulated, AB-like uplift) = ONE extra file, paired with the
            renaissance/optimistic scenario per the runbook's own scenario
            naming ("optimistic = deregulated"), NOT a 4th band (Open
            Decision #1, pre-resolved): at_retail_fraction_2030_renaissance
            _qcSundayDereg.csv. Mechanism: QC's Sunday profile is rescaled
            (shape held fixed, amplitude rescaled) so its peak-to-Saturday-
            peak ratio matches AB's own (AB has been deregulated since 1985,
            so AB's ratio is the "no trading-hours restriction" empirical
            reference), then the renaissance lever (1.05) is applied on top.

Deliverable files (outputs_step6/):
  at_retail_fraction_2030_{plateau,shift,renaissance}.csv
      columns: scenario, multiplier, day_type, DDAY_STRATA, slot (1-48),
               PR_GROUP (ALL/QC/AB), at_retail_fraction_2030_base,
               at_retail_fraction_2030_levered
  at_retail_fraction_2030_renaissance_qcSundayDereg.csv
      same schema, day_type=sunday / PR_GROUP=QC only, deregulated shape.

seed=42 (unused directly -- this script is deterministic/no-sampling, kept
for consistency with the calibration scripts' RNG discipline). pandas +
numpy only. CPU, seconds.
"""

from __future__ import annotations

import os
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "outputs_step6")

N_SLOTS = 48
RET = [f"ret30_{i:03d}" for i in range(1, N_SLOTS + 1)]
BANDS = ["conservative", "hybrid", "fullyhybrid"]
STRATUM_LABEL = {1: "weekday", 2: "saturday", 3: "sunday"}

LEVERS = {"plateau": 0.97, "shift": 0.90, "renaissance": 1.05}  # rel. 2022=1.00

QC_PR = 24
AB_PR = 48


def load_pooled_raw() -> tuple[pd.DataFrame, dict]:
    """Load the 3 raw per-band 2030 diaries; return pooled frame + per-band
    retail day-mean (evidence for gate 5.27, no-cross-contamination)."""
    frames = []
    per_band_mean = {}
    for band in BANDS:
        p = os.path.join(OUT_DIR, f"2030_diaries_{band}_raw.csv")
        df = pd.read_csv(p, usecols=RET + ["DDAY_STRATA", "PR"])
        per_band_mean[band] = float(df[RET].values.mean())
        frames.append(df)
    pooled = pd.concat(frames, ignore_index=True)
    return pooled, per_band_mean


def profile(df: pd.DataFrame, stratum: int, pr: int | None = None) -> np.ndarray:
    sub = df[df["DDAY_STRATA"] == stratum]
    if pr is not None:
        sub = sub[sub["PR"] == pr]
    if len(sub) == 0:
        return np.full(N_SLOTS, np.nan)
    return sub[RET].values.astype(float).mean(axis=0)


def main() -> None:
    print("=" * 70)
    print("3rdJ_06_retail_lever_4split.py -- retail scenario amplitude lever")
    print("=" * 70)

    pooled, per_band_mean = load_pooled_raw()
    print(f"\n[LOAD] Pooled raw 2030 rows: {len(pooled):,}")
    print("  Per-band retail (ret30) day-mean [gate 5.27 evidence -- office band "
          "should not move retail]:")
    for band, v in per_band_mean.items():
        print(f"    {band}: {v:.5f}")
    spread = max(per_band_mean.values()) - min(per_band_mean.values())
    print(f"  Cross-band spread: {spread:.5f} ({'OK, negligible' if spread < 0.001 else 'WARN, non-negligible'})")

    base_profiles = {s: profile(pooled, s) for s in (1, 2, 3)}
    base_profiles_qc = {s: profile(pooled, s, QC_PR) for s in (1, 2, 3)}
    base_profiles_ab = {s: profile(pooled, s, AB_PR) for s in (1, 2, 3)}

    # ── QC restricted-default diagnostic (natural, no manual file needed) ──────
    qc_sat_peak = float(np.nanmax(base_profiles_qc[2]))
    qc_sun_peak = float(np.nanmax(base_profiles_qc[3]))
    qc_ratio = qc_sun_peak / qc_sat_peak if qc_sat_peak > 0 else float("nan")
    ab_sat_peak = float(np.nanmax(base_profiles_ab[2]))
    ab_sun_peak = float(np.nanmax(base_profiles_ab[3]))
    ab_ratio = ab_sun_peak / ab_sat_peak if ab_sat_peak > 0 else float("nan")
    print(f"\n[QC-Sunday sub-axis] QC Sun/Sat peak ratio (base, restricted-default, "
          f"natural): {qc_ratio:.4f}  (spec window 0.60-0.75)")
    print(f"  AB Sun/Sat peak ratio (base, deregulated reference): {ab_ratio:.4f}")

    # ── 3 primary scenario files (ALL + QC + AB breakdown per day-type) ────────
    for scenario, mult in LEVERS.items():
        rows = []
        for s in (1, 2, 3):
            for grp, prof in (("ALL", base_profiles[s]), ("QC", base_profiles_qc[s]),
                               ("AB", base_profiles_ab[s])):
                for slot in range(N_SLOTS):
                    base_v = float(prof[slot])
                    rows.append({
                        "scenario": scenario, "multiplier": mult,
                        "day_type": STRATUM_LABEL[s], "DDAY_STRATA": s,
                        "slot": slot + 1, "PR_GROUP": grp,
                        "at_retail_fraction_2030_base": base_v,
                        "at_retail_fraction_2030_levered": base_v * mult,
                    })
        out = pd.DataFrame(rows)
        outp = os.path.join(OUT_DIR, f"at_retail_fraction_2030_{scenario}.csv")
        out.to_csv(outp, index=False)
        print(f"\n[WRITE] {outp}  rows={len(out):,}  multiplier={mult}")
        # lever-exactness self-check (gate 5.24 pre-flight)
        ratio_check = (out["at_retail_fraction_2030_levered"] /
                        out["at_retail_fraction_2030_base"].replace(0, np.nan))
        bad = ((ratio_check - mult).abs() > 0.01).sum()
        print(f"  Lever-exactness self-check: {bad} of {ratio_check.notna().sum()} "
              f"non-zero-base rows deviate from {mult} by > 0.01 (expect 0)")

    # ── Extra file: QC-Sunday deregulated, paired with renaissance/optimistic ──
    qc_sun_base = base_profiles_qc[3]
    scale = (ab_ratio * qc_sat_peak) / qc_sun_peak if (qc_sun_peak > 0 and not np.isnan(ab_ratio)) else 1.0
    qc_sun_dereg = qc_sun_base * scale
    mult_renaissance = LEVERS["renaissance"]
    rows = []
    for slot in range(N_SLOTS):
        base_v = float(qc_sun_dereg[slot])
        rows.append({
            "scenario": "renaissance", "multiplier": mult_renaissance,
            "day_type": "sunday", "DDAY_STRATA": 3, "slot": slot + 1,
            "PR_GROUP": "QC_DEREG",
            "at_retail_fraction_2030_base": base_v,
            "at_retail_fraction_2030_levered": base_v * mult_renaissance,
        })
    out_dereg = pd.DataFrame(rows)
    outp_dereg = os.path.join(OUT_DIR, "at_retail_fraction_2030_renaissance_qcSundayDereg.csv")
    out_dereg.to_csv(outp_dereg, index=False)
    dereg_new_ratio = float(np.nanmax(qc_sun_dereg)) / qc_sat_peak if qc_sat_peak > 0 else float("nan")
    print(f"\n[WRITE] {outp_dereg}  rows={len(out_dereg):,}")
    print(f"  Deregulated QC Sun/Sat peak ratio (target = AB's {ab_ratio:.4f}): "
          f"{dereg_new_ratio:.4f}  (restricted-default was {qc_ratio:.4f})")

    print("\nDONE.")


if __name__ == "__main__":
    main()
