# -*- coding: utf-8 -*-
"""Step 7, work item 7.2 -- the GRAMMAR side of `G7.10`.

`G7.10` compares two independently written recognisers for the same language on
10,000 sampled strings. `4thJ_step7_grammar.py:validate_record()` is one of them,
written by hand as a procedural checker. This module is the other: it emits an
**EBNF** the XGrammar back-end compiles and matches with, and it is written from
the language definition rather than from the checker.

🔴 **This module must never import `validate_record`.** If the two sides shared
code, `G7.10` would compare a thing to itself -- the `V5.d` / `V6.b` failure
class the parent document names explicitly. The only thing shared is
`build_alphabets()`, which is the constraint DEFINITION both sides are compiled
from; sharing that is the point, sharing the recogniser is the bug.

The 1440-minute sum is carried by the 145-state tally automaton written out as
145 nonterminals, `S0`..`S144`. That is what makes `RL12`'s regularity objection
answerable: the constraint is not arithmetic performed at match time, it is a
finite state set anyone can count in the emitted text.
"""

import importlib
import os
import random
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

_grammar = importlib.import_module("4thJ_step7_grammar")

DAY_MINUTES = _grammar.DAY_MINUTES
SLOT_MINUTES = _grammar.SLOT_MINUTES
N_TALLY_STATES = _grammar.N_TALLY_STATES          # 145
COP_MIN, COP_MAX = _grammar.COP_MIN, _grammar.COP_MAX
LOC_ALPHABET = _grammar.LOC_ALPHABET
N_PREFIX_FIELDS = _grammar.N_PREFIX_FIELDS        # 6

#: The characters a prefix field may contain. NOT arbitrary bytes: the shipped
#: prefixes carry `75+` and `11-14`, so `+` and `-` are in the class and dropping
#: either would reject real conditioning strings. Declared here because the
#: sampler draws from exactly this class -- a mismatch between the two would
#: register as a grammar disagreement when it is really a test artefact.
PREFIX_CHARS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_+-"
PREFIX_CLASS_EBNF = "[0-9a-zA-Z_+-]"


class EbnfError(ValueError):
    pass


def _lit(s):
    return '"' + s + '"'


def build_ebnf(alphabets, whole_record=True):
    """Return the EBNF text for the diary language, built from `alphabets`.

    Deliberately plain BNF: alternation, concatenation, one character class, and
    right recursion for the prefix fields. No `*`, no `?`, no optional groups.
    Every back-end reads this dialect the same way, and `G7.10`'s job is to find
    disagreements about the LANGUAGE, not about EBNF sugar.

    🔴 `whole_record` picks the ROOT, and it is not cosmetic -- see `FINDING 80`.
    `True` is the WHOLE RECORD, prefix included, and it is what the oracle checks
    and what `G7.10` compares. `False` is the COMPLETION ONLY, `S0 "<eor>"`, and
    it is what a decoder must be given: at generation time the prefix and its `|`
    are already in the PROMPT, so a mask rooted at the whole record starts matching
    the episodes against `PF`. `PFCHAR` is `[0-9a-zA-Z_+-]` and `PF` is unbounded,
    so that mask is satisfied by arbitrary word-like text and constrains nothing.
    """
    act = sorted(alphabets["act"])
    act2 = sorted(alphabets["act2"])
    loc = sorted(alphabets["loc"])
    cop = sorted(alphabets["cop"])

    if not act or not act2 or not loc or not cop:
        raise EbnfError("empty alphabet: act=%d act2=%d loc=%d cop=%d"
                        % (len(act), len(act2), len(loc), len(cop)))
    if set(loc) != set(LOC_ALPHABET):
        raise EbnfError("LOC alphabet drifted from the module constant: %s" % sorted(loc))

    lines = []
    lines.append("# 4J Step 7 diary grammar -- generated by 4thJ_step7_ebnf.py.")
    lines.append("# ACT %d | ACT2 %d | LOC %d | COP %d | tally states %d"
                 % (len(act), len(act2), len(loc), len(cop), N_TALLY_STATES))
    lines.append("")

    # --- the record -------------------------------------------------------
    if whole_record:
        pf = ' "," '.join(["PF"] * N_PREFIX_FIELDS)
        lines.append('root ::= %s "|" S0 "<eor>"' % pf)
        lines.append('PF ::= PFCHAR | PFCHAR PF')
        lines.append('PFCHAR ::= %s' % PREFIX_CLASS_EBNF)
    else:
        lines.insert(2, '# ROOT: COMPLETION ONLY. The prefix and its "|" are in the prompt.')
        lines.append('root ::= S0 "<eor>"')
    lines.append("")

    # --- terminal alphabets ----------------------------------------------
    lines.append("ACT ::= " + " | ".join(_lit(c) for c in act))
    lines.append("ACT2 ::= " + " | ".join(_lit(c) for c in act2))
    lines.append("LOC ::= " + " | ".join(_lit(c) for c in loc))
    lines.append("COP ::= " + " | ".join(_lit(str(c)) for c in cop))
    lines.append("")

    # --- one episode, minus its duration ----------------------------------
    # ACT2 may be empty -- `validate_record` accepts `act2 == ""`. Written as two
    # explicit alternatives rather than an optional group, so the empty case is
    # visible in the text instead of hidden in a `?`.
    lines.append('TAIL ::= "," ACT ",," LOC "," COP ";" '
                 '| "," ACT "," ACT2 "," LOC "," COP ";"')
    lines.append("")

    # --- 144 duration-carrying episode rules ------------------------------
    for k in range(1, N_TALLY_STATES):
        lines.append('E%d ::= "%d" TAIL' % (k, k * SLOT_MINUTES))
    lines.append("")

    # --- the 145-state tally ----------------------------------------------
    # S_s means "s slots already spent". A day is complete only on reaching 144,
    # so `S144` is never defined: the last episode of every accepting derivation
    # is the bare `E{144-s}` alternative. That is also why zero episodes cannot
    # parse -- `S0` has no empty production.
    for s in range(0, N_TALLY_STATES - 1):
        alts = ["E%d S%d" % (k, s + k) for k in range(1, N_TALLY_STATES - 1 - s)]
        alts.append("E%d" % (N_TALLY_STATES - 1 - s))
        lines.append("S%d ::= %s" % (s, " | ".join(alts)))

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# The sampled strings `G7.10` compares the two recognisers on.
# ---------------------------------------------------------------------------
def _out_of_alphabet(alphabet, width):
    """A code of the given width that is provably NOT in the alphabet.

    🔴 Computed, never chosen. The first run of the Step 7 self-test shipped `999`
    and `99` as "invalid" codes and both turned out to be REAL, so two negative
    cases proved nothing (`V4.f` vacuity). This searches instead of guessing, and
    raises rather than returning a code it could not prove absent.
    """
    for n in range(10 ** width):
        c = str(n).zfill(width)
        if c not in alphabet:
            return c
    raise EbnfError("every %d-digit code is in the alphabet; no negative case exists" % width)


def _random_prefix(rng):
    fields = []
    for _ in range(N_PREFIX_FIELDS):
        n = rng.randint(1, 8)
        fields.append("".join(rng.choice(PREFIX_CHARS) for _ in range(n)))
    return ",".join(fields)


def _random_durations(rng):
    """A partition of 1440 into positive multiples of 10."""
    k = rng.randint(1, 40)
    k = min(k, N_TALLY_STATES - 1)
    cuts = sorted(rng.sample(range(1, N_TALLY_STATES - 1), k - 1)) if k > 1 else []
    prev, out = 0, []
    for c in cuts + [N_TALLY_STATES - 1]:
        out.append((c - prev) * SLOT_MINUTES)
        prev = c
    return out


def _random_episode(rng, alphabets, dur):
    act = rng.choice(sorted(alphabets["act"]))
    act2 = "" if rng.random() < 0.3 else rng.choice(sorted(alphabets["act2"]))
    loc = rng.choice(sorted(alphabets["loc"]))
    cop = rng.choice(sorted(alphabets["cop"]))
    return "%d,%s,%s,%s,%d;" % (dur, act, act2, loc, cop)


def _valid_record(rng, alphabets):
    eps = "".join(_random_episode(rng, alphabets, d) for d in _random_durations(rng))
    return "%s|%s<eor>" % (_random_prefix(rng), eps)


def _split_episodes(text):
    body = text[: -len("<eor>")]
    prefix, eps = body.split("|", 1)
    chunks = eps.split(";")[:-1]
    return prefix, chunks


def _rejoin(prefix, chunks):
    return "%s|%s<eor>" % (prefix, "".join(c + ";" for c in chunks))


# Each mutator takes (valid_text, rng, alphabets) and returns a mutated string.
# Named so the report can say which class produced a disagreement.
def _mutators(alphabets):
    bad_act = _out_of_alphabet(alphabets["act"], 3)
    bad_act2 = _out_of_alphabet(alphabets["act2"], 2)

    def m_whitespace(t, rng, _a):
        i = rng.randint(0, len(t) - 1)
        return t[:i] + rng.choice(" \t\n") + t[i:]

    def m_no_eor(t, _r, _a):
        return t[: -len("<eor>")]

    def m_no_bar(t, _r, _a):
        return t.replace("|", "", 1)

    def m_prefix_short(t, _r, _a):
        p, c = _split_episodes(t)
        return _rejoin(",".join(p.split(",")[:-1]), c)

    def m_prefix_long(t, _r, _a):
        p, c = _split_episodes(t)
        return _rejoin(p + ",extra", c)

    def m_prefix_empty(t, rng, _a):
        p, c = _split_episodes(t)
        f = p.split(",")
        f[rng.randrange(len(f))] = ""
        return _rejoin(",".join(f), c)

    def m_zero_episodes(t, _r, _a):
        p, _c = _split_episodes(t)
        return "%s|<eor>" % p

    def m_no_terminal_semi(t, _r, _a):
        p, c = _split_episodes(t)
        return "%s|%s<eor>" % (p, "".join(x + ";" for x in c)[:-1])

    def m_episode_short(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        c[i] = ",".join(c[i].split(",")[:-1])
        return _rejoin(p, c)

    def m_episode_long(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        c[i] = c[i] + ",9"
        return _rejoin(p, c)

    def m_dur_not_mult10(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        f = c[i].split(",")
        f[0] = str(int(f[0]) + rng.randint(1, 9))
        c[i] = ",".join(f)
        return _rejoin(p, c)

    def m_dur_leading_zero(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        f = c[i].split(",")
        f[0] = "0" + f[0]
        c[i] = ",".join(f)
        return _rejoin(p, c)

    def m_day_short(t, rng, _a):
        p, c = _split_episodes(t)
        if len(c) == 1:
            f = c[0].split(",")
            f[0] = str(int(f[0]) - SLOT_MINUTES) if int(f[0]) > SLOT_MINUTES else "10"
            c[0] = ",".join(f)
            return _rejoin(p, c)
        return _rejoin(p, c[:-1])

    def m_day_long(t, rng, _a):
        p, c = _split_episodes(t)
        return _rejoin(p, c + [c[rng.randrange(len(c))]])

    def m_bad_act(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        f = c[i].split(",")
        f[1] = bad_act
        c[i] = ",".join(f)
        return _rejoin(p, c)

    def m_bad_act2(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        f = c[i].split(",")
        f[2] = bad_act2
        c[i] = ",".join(f)
        return _rejoin(p, c)

    def m_bad_loc(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        f = c[i].split(",")
        f[3] = "workplace"        # the class Step 2 does not emit -- see D-S7-2
        c[i] = ",".join(f)
        return _rejoin(p, c)

    def m_cop_range(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        f = c[i].split(",")
        f[4] = str(COP_MAX + 1 + rng.randint(0, 30))
        c[i] = ",".join(f)
        return _rejoin(p, c)

    def m_cop_leading_zero(t, rng, _a):
        p, c = _split_episodes(t)
        i = rng.randrange(len(c))
        f = c[i].split(",")
        f[4] = "0" + f[4]
        c[i] = ",".join(f)
        return _rejoin(p, c)

    return [
        ("whitespace", m_whitespace), ("no_eor", m_no_eor), ("no_bar", m_no_bar),
        ("prefix_short", m_prefix_short), ("prefix_long", m_prefix_long),
        ("prefix_empty", m_prefix_empty), ("zero_episodes", m_zero_episodes),
        ("no_terminal_semi", m_no_terminal_semi),
        ("episode_short", m_episode_short), ("episode_long", m_episode_long),
        ("dur_not_mult10", m_dur_not_mult10), ("dur_leading_zero", m_dur_leading_zero),
        ("day_short", m_day_short), ("day_long", m_day_long),
        ("bad_act", m_bad_act), ("bad_act2", m_bad_act2), ("bad_loc", m_bad_loc),
        ("cop_range", m_cop_range), ("cop_leading_zero", m_cop_leading_zero),
    ]


def sample_strings(alphabets, n=10000, seed=20260822, valid_share=0.5):
    """Return [(label, text)] -- reproducible for a given seed.

    `V7.e`: the set must contain known-invalid strings. Half the sample is
    mutated on purpose, every mutator class appears, and the caller is expected
    to check that the oracle actually rejects some of them rather than assuming
    a mutation is a rejection.
    """
    rng = random.Random(seed)
    muts = _mutators(alphabets)
    out = []
    n_valid = int(n * valid_share)
    for _ in range(n_valid):
        out.append(("valid", _valid_record(rng, alphabets)))
    for i in range(n - n_valid):
        name, fn = muts[i % len(muts)]
        base = _valid_record(rng, alphabets)
        try:
            out.append((name, fn(base, rng, alphabets)))
        except Exception as e:                     # a mutator that cannot fire is a gap
            out.append(("MUTATOR_FAILED:%s:%s" % (name, type(e).__name__), base))
    rng.shuffle(out)
    return out


if __name__ == "__main__":
    print("Library module. Run 4thJ_step7_ebnf_selftest.py for its unit tests.",
          file=sys.stderr)
