#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
figS03_pipeline.py -- Figure S3: The Two-Channel Construction Pipeline, in Full.

Generates:
  writing/figures/SI/Figure_S03_leg2_pipeline.png
  writing/figures/SI/Figure_S03_leg2_pipeline.pdf
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from fig_style import SLATE, TEAL, GREY, AMBER, INK, WHITE, new_fig, box, arrow, footnote, save_both, wrap_text
from matplotlib.patches import Rectangle, FancyBboxPatch

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Figure_S03_leg2_pipeline")

def main():
    W, H = 18.0, 7.0
    fig, ax = new_fig(W, H)

    # Title / Caption
    ax.text(W / 2.0, H - 0.5, "The Two-Channel Construction Pipeline, in Full", ha="center", va="top",
            fontsize=12, weight="bold", color=INK)

    stages = [
        "Data Collection",
        "Harmonization",
        "Merge & Tiling",
        "Two-Head\nTransformer",
        "Archetype Linkage",
        "Forecast 2030",
        "BEM Integration",
        "BEM Simulation",
        "End-Use Loads"
    ]

    n_stages = len(stages)
    box_w = 1.6
    box_h = 2.4
    gap = 0.3
    start_x = 0.5
    y_center = 3.5

    for i, name in enumerate(stages):
        bx = start_x + i * (box_w + gap)
        by = y_center - box_h / 2.0

        # Draw outer box
        patch = FancyBboxPatch((bx, by), box_w, box_h, boxstyle="round,pad=0.0,rounding_size=0.15",
                               linewidth=1.2, edgecolor=INK, facecolor="#F8F6F0", zorder=3)
        ax.add_patch(patch)

        # Stage number & label
        ax.text(bx + 0.1, by + box_h - 0.15, f"STEP {i+1}", fontsize=6.5, weight="bold", color=GREY, va="top")
        ax.text(bx + box_w / 2.0, by + box_h - 0.5, name, fontsize=8.0, weight="bold", color=INK, ha="center", va="top")

        # Channels inside stage boxes (stages 3 to 9)
        if i >= 2:
            # Residential lane (slate)
            ax.add_patch(Rectangle((bx + 0.15, by + 1.0), box_w - 0.3, 0.4, facecolor=SLATE, edgecolor=INK, linewidth=0.8, zorder=4))
            ax.text(bx + box_w / 2.0, by + 1.2, "residential", fontsize=6.5, color=WHITE, weight="bold", ha="center", va="center", zorder=5)

            # Office lane (teal)
            ax.add_patch(Rectangle((bx + 0.15, by + 0.3), box_w - 0.3, 0.4, facecolor=TEAL, edgecolor=INK, linewidth=0.8, zorder=4))
            ax.text(bx + box_w / 2.0, by + 0.5, "office", fontsize=6.5, color=WHITE, weight="bold", ha="center", va="center", zorder=5)

            # Stage 7 divergence details
            if i == 6:
                # REPLACE badge for residential
                ax.text(bx + box_w / 2.0, by + 1.2, "REPLACE", fontsize=6.5, color=WHITE, weight="bold", ha="center", va="center", zorder=5)
                # MODULATE badge for office
                ax.text(bx + box_w / 2.0, by + 0.5, "MODULATE", fontsize=6.5, color=WHITE, weight="bold", ha="center", va="center", zorder=5)

        # Connectors between boxes
        if i < n_stages - 1:
            arrow(ax, (bx + box_w, y_center), (bx + box_w + gap, y_center), color=INK, lw=1.2)

    # Wiring verification badge under Stage 7
    s7_x = start_x + 6 * (box_w + gap) + box_w / 2.0
    badge_y = y_center - box_h / 2.0 - 0.7
    ax.add_patch(FancyBboxPatch((s7_x - 1.0, badge_y), 2.0, 0.5, boxstyle="round,pad=0.0,rounding_size=0.1",
                           linewidth=1.0, edgecolor=INK, facecolor="#FFF8DC", zorder=4))
    ax.text(s7_x, badge_y + 0.25, "[✓] wiring verification", fontsize=7.5, weight="bold", color=INK, ha="center", va="center", zorder=5)
    ax.plot([s7_x, s7_x], [y_center - box_h / 2.0, badge_y + 0.5], color=INK, linewidth=1.0, linestyle="dashed", zorder=3)

    # Legend
    leg_x = W - 3.5
    leg_y = 0.5
    ax.add_patch(Rectangle((leg_x, leg_y), 0.3, 0.2, facecolor=SLATE, edgecolor=INK, linewidth=0.8))
    ax.text(leg_x + 0.4, leg_y + 0.1, "residential", fontsize=7.5, color=INK, va="center")
    ax.add_patch(Rectangle((leg_x + 1.5, leg_y), 0.3, 0.2, facecolor=TEAL, edgecolor=INK, linewidth=0.8))
    ax.text(leg_x + 1.9, leg_y + 0.1, "office", fontsize=7.5, color=INK, va="center")

    footnote(ax, W, 0.15,
             "Two-channel construction stage in full: residential & office presence generated by a two-head conditional generator",
             fontsize=8.0, color=INK)

    save_both(fig, OUT)

if __name__ == "__main__":
    main()
