#!/bin/bash
SIF=/speed-scratch/o_iseri/step9_spike/energyplus_24.2.0.sif
EP_BIN=/EnergyPlus-24.2.0-94a887817b-Linux-Ubuntu22.04-x86_64
exec singularity exec --bind /speed-scratch --bind /nfs/speed-scratch "$SIF" "$EP_BIN/ExpandObjects" "$@"
